project:
  type: website

website:
  title: "playfair-reproduction"
  navbar:
    title: false
    collapse-below: lg
    background: light
    search: false
    tools:
      - icon: github
        href: https://github.com/linogaliana/playfair-viz-reproduction.git
        text: Code source sur GitHub

format:
  html:
    respect-user-color-scheme: true
    css: styles.css
    toc: true
    theme:
      light: [cosmo]
      dark: [cosmo, styles/custom.scss]




